//比赛筛选action
export const ACTIVE_ALL_FILTER = 'ACTIVE_ALL_FILTER'
export const ACTIVE_A_FILTERS = 'ACTIVE_A_FILTERS'
export const INIT_FILTERS = 'INIT_FILTERS'
export const DISABLE_ALL_FILTER = 'DISABLE_ALL_FILTER'

//比赛目录数据
export const INIT_CATALOG = 'INIT_CATALOG'
export const SWITCH_CATALOG = 'SWITCH_CATALOG'

//比赛列表数据
export const GETGAMELIST_REQUEST = 'GETGAMELIST_REQUEST'
export const GETGAMELIST_SUCCESS = 'GETGAMELIST_SUCCESS'
export const GETGAMELIST_FAILURE = 'GETGAMELIST_FAILURE'

